const XCOMBO_KODER = [
  { kode: "3743 0005", funksjon: "Slår på automatisk klimastyring og endrer varsler/førerovervåking ved oppstart", merknad: "Populær 'før kjøring'-combo fra forumet" },
  { kode: "3471 0000... (ufullstendig)", funksjon: "'Vor Fahrtbeginn' - endrer føreroverøvåking, startvarsel m.m. når du setter deg inn", merknad: "Delt på XCombos, svært populær der" },
  { kode: "2938 0034", funksjon: "Setter en rekke foretrukne innstillinger automatisk ved oppstart", merknad: "Forumbrukere beskriver den som oppstart uten ekstra popup/bekreftelse" },
  { kode: "6497 0007", funksjon: "Klima, setevarme/ventilasjon og rattvarme basert på utetemperatur", merknad: "En av de mer nyttige helårs-comboene" },
  { kode: "8155 0044", funksjon: "Slår på alle klimadyser - ansikt, føtter og frontrute", merknad: "Spesifikt oppgitt testet/laget for G6 Facelift" },
  { kode: "5508 0048", funksjon: "Starter kraftig kjøling dersom kupeen er ≥30°C", merknad: "Kontrollerer temperaturen periodisk og kjører maks kjøling i 15 min" },
  { kode: "0002 0013", funksjon: "Automatisk vinteroppvarming under en valgt kupétemperatur", merknad: "Kan inkludere maks varme, setevarme og speil/bakrutevarme" },
  { kode: "8512 0000... (ufullstendig)", funksjon: "Automatisk vinteroppvarming", merknad: "Aktiverer sete- og rattvarme etter utetemperatur" },
  { kode: "5753 0000... (ufullstendig)", funksjon: "Intelligent rattvarme når fører setter seg inn", merknad: "Temperatur-/situasjonsavhengig" },
  { kode: "2475 0000... (ufullstendig)", funksjon: "Automatisk klimastyring basert på utetemperatur", merknad: "Kan tilpasses egne temperaturgrenser" },
  { kode: "0728 0000... (ufullstendig)", funksjon: "Slår av setevarme, ventilasjon og massasje når setet blir tomt", merknad: "Praktisk for energisparing, laget av en G6 Facelift-eier" },
  { kode: "9096 0007", funksjon: "Bilvaskmodus", merknad: "Lukker vinduer, låser dører, minner om viskere/N og folder speil ved N" },
  { kode: "2485 0004 / 6789 0004", funksjon: "Alternativ bilvask-workflow", merknad: "Manuell start, lukker bil og håndterer speil/N/D-sekvens" },
  { kode: "3995 0000... (ufullstendig)", funksjon: "Felg-/hjulkamera automatisk ved 0-20 km/t", merknad: "En av de kuleste for parkering" },
  { kode: "1016 0001", funksjon: "Flytter førersetet bakover når døren åpnes", merknad: "Laget som 'komfortinnstigning' for høye førere" },
  { kode: "7272 0001", funksjon: "Flytter setet tilbake til definert kjørestilling", merknad: "Passer sammen med 1016 0001" },
  { kode: "8205 0005", funksjon: "Automatisk styring av utvendig lys etter gir og lysforhold", merknad: "D/R → park/nærlys etter forhold; P → av" },
  { kode: "9797 0000... (ufullstendig)", funksjon: "Slår på nærlys når viskerne brukes", merknad: "Reagerer på Auto/Lo/Hi-viskerstatus" },
  { kode: "5752 0000... (ufullstendig)", funksjon: "Parklys på når bilen står parkert og fører sitter i bilen", merknad: "Skifter tilbake til autolys ved kjøring" },
  { kode: "7512 0000... (ufullstendig)", funksjon: "Aktiverer Sentry Mode automatisk når du forlater bilen", merknad: "Forsterket advarsel om forbruksvisningen ikke resettes" },
  { kode: "0053 0000... (ufullstendig)", funksjon: "Avslutter lading og låser opp ladeport når valgt dør åpnes", merknad: "Smart dersom du ofte kobler fra etter å ha hentet noe i bilen" },
  { kode: "7549 0000... (ufullstendig)", funksjon: "Åpner ladeport automatisk når du kommer hjem", merknad: "Bruker posisjon/hjemmeområde" },
  { kode: "1402 0000... (ufullstendig)", funksjon: "Varsler ca. 5 minutter før lading er ferdig", merknad: "Enkel, men nyttig" },
  { kode: "5568 0000... (ufullstendig)", funksjon: "Påminnelse om å lade når rekkevidden faller under ca. 100 km", merknad: "'Ikke glem å lade'-trigger" },
  { kode: "8556 0000... (ufullstendig)", funksjon: "Endrer regenerering etter hastighet", merknad: "Hastighets-/temperaturavhengig regenereringsstyring" },
  { kode: "8343 0000... (ufullstendig)", funksjon: "Senker medievolum til 1 når fører åpner døren og ingen andre sitter i bilen", merknad: "Media ved døråpning" },
  { kode: "2229 0000... (ufullstendig)", funksjon: "Senker medievolum når en dør åpnes og setter det tilbake etterpå", merknad: "Mer avansert variant av 8343" },
  { kode: "1767 0000... (ufullstendig)", funksjon: "Slår bilens Wi-Fi-hotspot av/på etter at fører har satt seg og festet beltet", merknad: "Automatisk hotspot" },
  { kode: "2579 0000... (ufullstendig)", funksjon: "Setter medievolum og aktiverer hotspot ved innstigning", merknad: "For bedre CarPlay-opplevelse" },
  { kode: "2636 0031", funksjon: "Musikk/radio automatisk når du setter deg inn", merknad: "Noen G6-eiere sier dette allerede skjer uten XCOMBO" },
  { kode: "6243 0023", funksjon: "Trigger ved opplåsing", merknad: "Laget for å starte en annen XCOMBO når bilen låses opp" }
];
